{
 "title": "Active Users",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Any unhandled exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"exception\"} |= ``"
    }
   ]
  },
  {
   "title": "Factory service requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"factory-req\"} |= ``"
    }
   ]
  },
  {
   "title": "Database requests (SQL queries)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"db-query\"} |= ``"
    }
   ]
  },
  {
   "title": "HTTP Requests (HTTP method, path, status code, If the request has an authorization header, Request body, Response body)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"http-req\"} |= ``"
    }
   ]
  },
  {
   "title": "Total Revenue (Accumulated per Minute)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revenuePerMinute_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Purchases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "PizzaPurchases", "legendFormat": "__auto" },
    {
     "expr": "PizzaCreationFailure_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(Authentication_Failure_minute_requests_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_attempts_success_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "PizzaCreationLatency_requests_per_min",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(http_request_latency_ms_milliseconds[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(http_requests_delete_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_get_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_post_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_put_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  }
 ]
}