{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "ListObjectsInBucket",
			"Effect": "Allow",
			"Action": [
				"s3:ListBucket"
			],
			"Resource": [
				"arn:aws:s3:::pizza.jonahkunzler.click"
			]
		},
		{
			"Sid": "UpdateS3Bucket",
			"Effect": "Allow",
			"Action": [
				"s3:*Object"
			],
			"Resource": [
				"arn:aws:s3:::pizza.jonahkunzler.click/*"
			]
		},
		{
			"Sid": "InvalidateCloudFront",
			"Effect": "Allow",
			"Action": [
				"cloudfront:CreateInvalidation"
			],
			"Resource": [
				"arn:aws:cloudfront::752651706073:distribution/E31T8CLZVJTQN"
			]
		},
		{
			"Sid": "AuthenticateWithECR",
			"Effect": "Allow",
			"Action": [
				"ecr:GetAuthorizationToken"
			],
			"Resource": "*"
		},
		{
			"Sid": "PushToECR",
			"Effect": "Allow",
			"Action": [
				"ecr:BatchGetImage",
				"ecr:BatchCheckLayerAvailability",
				"ecr:PutImage",
				"ecr:InitiateLayerUpload",
				"ecr:UploadLayerPart",
				"ecr:CompleteLayerUpload"
			],
			"Resource": [
				"arn:aws:ecr:us-east-1:752651706073:repository/jwt-pizza-service"
			]
		},
		{
			"Sid": "DeployContainer",
			"Effect": "Allow",
			"Action": [
				"ecs:UpdateService"
			],
			"Resource": [
				"arn:aws:ecs:us-east-1:752651706073:service/jwt-pizza-service/jwt-pizza-service"
			]
		},
		{
			"Sid": "PassRolesInTaskDefinition",
			"Effect": "Allow",
			"Action": [
				"iam:PassRole"
			],
			"Resource": [
				"arn:aws:iam::752651706073:role/jwt-pizza-ecs"
			]
		}
	]
}
